### PR TITLE
ENH: Add ITKImportImageStack

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by imikejackson** [comment]
Was this branch ready for merge into the main repo?

**Comment by thewtex** [comment]
Still needs more work.

**Comment by fbudin69500** [comment]
Unused variable:

https://github.com/thewtex/ITKImageProcessing/blob/f6ab72feedd28cab7f4aec9b2d5765bac03d7682/ITKImageProcessingFilters/ITKImportImageStack.cpp#L174

**Comment by fbudin69500** [comment]
When using the plugin: "Padding Digits" is initialized to 0. Pressing the up arrow once changes the value to '2'. Pressing the down arrow goes down to 1.

**Comment by fbudin69500** [comment]
It would be nice to be able to select: Data Container, Cell Attribute Matrix, and Image Data (see Image Reader)

**Comment by thewtex** [comment]
> Unused variable:

Addressed.

> When using the plugin: "Padding Digits" is initialized to 0. Pressing the up arrow once changes the value to '2'. Pressing the down arrow goes down to 1.

This behavior seems to be particular to the data set worked with, but it is in the general FileListInfo code and unrelated to this PR.

> It would be nice to be able to select: Data Container, Cell Attribute Matrix, and Image Data (see Image Reader)

This is there -- it is at the bottom of the filter UI.

**Review by fbudin69500 — APPROVED** [review]

**Comment by fbudin69500** [comment]
+1

**Review by fbudin69500 — APPROVED** [review]

**Review by fbudin69500 — APPROVED** [review]
Good catch. I was wondering why the exception message was not printed...

**Pull request merged**
