### PR TITLE
Update CircleCI configuration to 2.0

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by imikejackson** [comment]
Are the docker images that are going to be used updated? Last time I checked I think they were based on Ubuntu 14? We need at least Ubuntu 16.04 or GCC 5.x to compile DREAM.3D. We raised the minimum a few weeks back. GCC 4.8.5 is now deprecated.

Thanks for updating the configuration. I just wish we could get enough compute time at Circle CI to compile dream3d. I may need to figure out how to do builds with just a few of the plugins enabled.

**Comment by thewtex** [comment]
Yes, moving away from CircleCI to Azure Pipelines to avoid the time out issues is a good idea in the long run. Azure Pipelines supports all three major platforms, has two decent cores for builds, and a timeout of three hours. The DREAM.3D build is likely feasible...

**Comment by imikejackson** [comment]
We should get together to figure out an Azure Pipeline. We were also thinking about writing some "in house" code to listen to GitHub events through a service such as ngrok so that our internal machines would kick off builds when PR's are submitted.

**Comment by thewtex** [comment]
Yes -- Azure Pipelines hosted systems can likely due the job. But, Azure Pipelines also supports using on premise system a la Jenkins, which you could point to your internal systems. Then you do not need ngrok, and all the GitHub integration, reporting, monitoring, etc. are available.

**Comment by imikejackson** [comment]
I was literally just reading about Azure Agents. This may be the approach to take for us. I just need to find the time to sit down and figure it all out.

**Pull request merged**
