### PR TITLE
ENH: Add ITKMorphologicalWaterShedImage

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
Yes!

**Review by thewtex — CHANGES_REQUESTED** [review]
Oops -- reviewed too quick -- the other filters need to be re-enabled.

**Comment by fbudin69500** [comment]
I had locally but I forgot to add the CMake files in the commit... Solved.

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
:100:

**Pull request merged**
