### PR TITLE
 Add ProxTVImage filter

### PR DESCRIPTION
**Pull request by dzenanz**
This fails to compile on my computer:
```text
1>------ Build started: Project: ITKImageProcessingServer, Configuration: Debug x64 ------
1>Automatic MOC for target ITKImageProcessingServer
1>mocs_compilation.cpp
1>ITKProxTVImage.cpp
1>ITKImageProcessingPlugin.cpp
1>C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing/ITKImageProcessingFilters/ITKProxTVImage.h(22): fatal error C1083: Cannot open include file: 'itkProxTVImageFilter.h': No such file or directory (compiling source file C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing\ITKImageProcessingFilters\ITKProxTVImage.cpp)
1>C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing/ITKImageProcessingFilters/ITKProxTVImage.h(22): fatal error C1083: Cannot open include file: 'itkProxTVImageFilter.h': No such file or directory (compiling source file C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing\ITKImageProcessingPlugin.cpp)
1>c:\misc\bluequartz\dream3d-rel\plugins\itkimageprocessing\itkimageprocessingserver_autogen\include_debug\phpl5bjagh\../../../../../../DREAM3D_Plugins/ITKImageProcessing/ITKImageProcessingFilters/ITKProxTVImage.h(22): fatal error C1083: Cannot open include file: 'itkProxTVImageFilter.h': No such file or directory (compiling source file C:\Misc\BlueQuartz\DREAM3D-rel\Plugins\ITKImageProcessing\ITKImageProcessingServer_autogen\mocs_compilation.cpp)
1>Done building project "ITKImageProcessingServer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 7 up-to-date, 0 skipped ==========
```
Indeed, the proper include directory is missing from the list of additional include directories. I will do a new clean build to see whether that will help. https://github.com/BlueQuartzSoftware/DREAM3DSuperbuild/pull/17 is a prerequisite for this.

### CODE REVIEW

**Comment by dzenanz** [comment]
Clean build did not help, I get the same errors:
```text
1>------ Build started: Project: ZZ_ITKIOVTK_DLL_DEBUG-Copy, Configuration: Debug x64 ------
2>------ Build started: Project: ZZ_ITKOptimizers_DLL_DEBUG-Copy, Configuration: Debug x64 ------
3>------ Build started: Project: ZZ_ITKStatistics_DLL_DEBUG-Copy, Configuration: Debug x64 ------
4>------ Build started: Project: ZZ_ITKTransform_DLL_DEBUG-Copy, Configuration: Debug x64 ------
5>------ Build started: Project: ZZ_ITKWatersheds_DLL_DEBUG-Copy, Configuration: Debug x64 ------
6>------ Build started: Project: ZZ_Montage_DLL_DEBUG-Copy, Configuration: Debug x64 ------
7>------ Build started: Project: ZZ_QWT_LIBRARY_DLL_Debug-Copy, Configuration: Debug x64 ------
8>------ Build started: Project: ZZ_QWT_LIBRARY_DLL_Release-Copy, Configuration: Debug x64 ------
9>------ Build started: Project: ZZ_Qt5Concurrent-Release-Copy, Configuration: Debug x64 ------
10>------ Build started: Project: ZZ_Qt5Concurrentd-Debug-Copy, Configuration: Debug x64 ------
11>------ Build started: Project: ZZ_Qt5Core-Release-Copy, Configuration: Debug x64 ------
12>------ Build started: Project: ZZ_Qt5Cored-Debug-Copy, Configuration: Debug x64 ------
13>------ Build started: Project: ZZ_Qt5Gui-Release-Copy, Configuration: Debug x64 ------
14>------ Build started: Project: ZZ_Qt5Guid-Debug-Copy, Configuration: Debug x64 ------
15>------ Build started: Project: ITKImageProcessingServer, Configuration: Debug x64 ------
16>------ Build started: Project: ZZ_Qt5Network-Release-Copy, Configuration: Debug x64 ------
7>  Copy: C:/Misc/BlueQuartz/SDK/qwt-6.1.3-5.12.3/lib/qwtd.dll    To: C:/Misc/BlueQuartz/DREAM3D-build/Bin/Debug/
8>  Copy: C:/Misc/BlueQuartz/SDK/qwt-6.1.3-5.12.3/lib/qwt.dll    To: C:/Misc/BlueQuartz/DREAM3D-build/Bin/Release/
17>------ Build started: Project: ZZ_Qt5OpenGL-Release-Copy, Configuration: Debug x64 ------
18>------ Build started: Project: ZZ_Qt5OpenGLd-Debug-Copy, Configuration: Debug x64 ------
19>------ Build started: Project: ZZ_Qt5PrintSupport-Release-Copy, Configuration: Debug x64 ------
20>------ Build started: Project: ZZ_Qt5PrintSupportd-Debug-Copy, Configuration: Debug x64 ------
21>------ Build started: Project: ZZ_Qt5Sql-Release-Copy, Configuration: Debug x64 ------
22>------ Build started: Project: ZZ_Qt5Sqld-Debug-Copy, Configuration: Debug x64 ------
23>------ Build started: Project: ZZ_Qt5Svg-Release-Copy, Configuration: Debug x64 ------
24>------ Build started: Project: ZZ_Qt5Svgd-Debug-Copy, Configuration: Debug x64 ------
25>------ Build started: Project: ZZ_Qt5Widgets-Release-Copy, Configuration: Debug x64 ------
26>------ Build started: Project: ZZ_Qt5Widgetsd-Debug-Copy, Configuration: Debug x64 ------
27>------ Build started: Project: ZZ_Qt5Xml-Release-Copy, Configuration: Debug x64 ------
28>------ Build started: Project: ZZ_Qt5Xmld-Debug-Copy, Configuration: Debug x64 ------
29>------ Build started: Project: ZZ_libharu_LIB_DLL_DEBUG-Copy, Configuration: Debug x64 ------
30>------ Build started: Project: ZZ_tbb_DLL_DEBUG-Copy, Configuration: Debug x64 ------
31>------ Build started: Project: ZZ_tbb_DLL_RELEASE-Copy, Configuration: Debug x64 ------
32>------ Build started: Project: ZZ_tbbmalloc_DLL_DEBUG-Copy, Configuration: Debug x64 ------
33>------ Build started: Project: ZZ_tbbmalloc_DLL_RELEASE-Copy, Configuration: Debug x64 ------
34>------ Build started: Project: DataFolderCopy, Configuration: Debug x64 ------
35>------ Build started: Project: ITKImageProcessingDataFolderCopy, Configuration: Debug x64 ------
36>------ Build started: Project: ITKImageProcessingExamplePipelinesCopy, Configuration: Debug x64 ------
37>------ Build started: Project: OrientationAnalysisDataFolderCopy, Configuration: Debug x64 ------
38>------ Build started: Project: PrebuiltPipelinesCopy, Configuration: Debug x64 ------
39>------ Build started: Project: ZZ_Qt5Networkd-Debug-Copy, Configuration: Debug x64 ------
40>------ Build started: Project: SIMPLDataFolderCopy, Configuration: Debug x64 ------
41>------ Build started: Project: SIMPLExamplePipelinesCopy, Configuration: Debug x64 ------
42>------ Build started: Project: ZZ_HDF5_CPP_LIB_DLL_DEBUG-Copy, Configuration: Debug x64 ------
35>Copying ITKImageProcessing Data Folder into Binary Directory
43>------ Build started: Project: ZZ_HDF5_LIB_DLL_DEBUG-Copy, Configuration: Debug x64 ------
44>------ Build started: Project: ZZ_ITKCommon_DLL_DEBUG-Copy, Configuration: Debug x64 ------
45>------ Build started: Project: ZZ_ITKIOBMP_DLL_DEBUG-Copy, Configuration: Debug x64 ------
46>------ Build started: Project: ZZ_ITKIOBioRad_DLL_DEBUG-Copy, Configuration: Debug x64 ------
40>Copying SIMPL Data Folder into Binary Directory
47>------ Build started: Project: ZZ_ITKIOGE_DLL_DEBUG-Copy, Configuration: Debug x64 ------
41>Copying SIMPL Example Pipelines into Binary Directory
36>Copying ITKImageProcessing Example Pipelines into Binary Directory
48>------ Build started: Project: ZZ_ITKIOGIPL_DLL_DEBUG-Copy, Configuration: Debug x64 ------
49>------ Build started: Project: ZZ_ITKIOIPL_DLL_DEBUG-Copy, Configuration: Debug x64 ------
50>------ Build started: Project: ZZ_ITKIOImageBase_DLL_DEBUG-Copy, Configuration: Debug x64 ------
37>Copying OrientationAnalysis Data Folder into Binary Directory
51>------ Build started: Project: ZZ_ITKIOJPEG_DLL_DEBUG-Copy, Configuration: Debug x64 ------
52>------ Build started: Project: ZZ_ITKIOMRC_DLL_DEBUG-Copy, Configuration: Debug x64 ------
38>Copying Prebuilt Pipelines into Binary Directory
53>------ Build started: Project: ZZ_ITKIOMeta_DLL_DEBUG-Copy, Configuration: Debug x64 ------
54>------ Build started: Project: ZZ_ITKIONIFTI_DLL_DEBUG-Copy, Configuration: Debug x64 ------
55>------ Build started: Project: ZZ_ITKIONRRD_DLL_DEBUG-Copy, Configuration: Debug x64 ------
56>------ Build started: Project: ZZ_ITKIOPNG_DLL_DEBUG-Copy, Configuration: Debug x64 ------
57>------ Build started: Project: ZZ_ITKIOStimulate_DLL_DEBUG-Copy, Configuration: Debug x64 ------
58>------ Build started: Project: ZZ_ITKIOTIFF_DLL_DEBUG-Copy, Configuration: Debug x64 ------
15>Automatic MOC for target ITKImageProcessingServer
15>mocs_compilation.cpp
15>ITKProxTVImage.cpp
15>ITKImageProcessingPlugin.cpp
34>Copying Data Folder into Binary Directory
15>C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing/ITKImageProcessingFilters/ITKProxTVImage.h(22,10): error C1083:  Cannot open include file: 'itkProxTVImageFilter.h': No such file or directory (compiling source file C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing\ITKImageProcessingFilters\ITKProxTVImage.cpp)
15>C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing/ITKImageProcessingFilters/ITKProxTVImage.h(22,10): error C1083:  Cannot open include file: 'itkProxTVImageFilter.h': No such file or directory (compiling source file C:\Misc\BlueQuartz\DREAM3D_Plugins\ITKImageProcessing\ITKImageProcessingPlugin.cpp)
15>C:\Misc\BlueQuartz\DREAM3D-build\Plugins\ITKImageProcessing\ITKImageProcessingServer_autogen\include_Debug\PHPL5BJAGH\../../../../../../DREAM3D_Plugins/ITKImageProcessing/ITKImageProcessingFilters/ITKProxTVImage.h(22,10): error C1083:  Cannot open include file: 'itkProxTVImageFilter.h': No such file or directory (compiling source file C:\Misc\BlueQuartz\DREAM3D-build\Plugins\ITKImageProcessing\ITKImageProcessingServer_autogen\mocs_compilation.cpp)
15>Done building project "ITKImageProcessingServer.vcxproj" -- FAILED.
59>------ Build started: Project: ITKImageProcessingGui, Configuration: Debug x64 ------
59>Automatic MOC for target ITKImageProcessingGui
59>LINK : fatal error LNK1104: cannot open file '..\..\Bin\Debug\ITKImageProcessing_plugin_debug.lib'
59>Done building project "ITKImageProcessingGui.vcxproj" -- FAILED.
60>------ Build started: Project: ITKImageProcessingUnitTest, Configuration: Debug x64 ------
60>Automatic MOC for target ITKImageProcessingUnitTest
60>LINK : fatal error LNK1104: cannot open file '..\..\Bin\Debug\ITKImageProcessing_plugin_debug.lib'
60>Done building project "ITKImageProcessingUnitTest.vcxproj" -- FAILED.
61>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
61>Project not selected to build for this solution configuration 
62>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
62>Project not selected to build for this solution configuration 
========== Build: 57 succeeded, 3 failed, 39 up-to-date, 2 skipped ==========
```

**Comment by imikejackson** [comment]
It looks like we are not percolating the list of include directories into the ITKImageProcessingServer target based on the ITK Modules that are needed. My guess is that there is some missing CMake code for the ITKImageProcessingServer target that needs to have the ITKTotalVariation module as a "target_include_directories"

**Comment by dzenanz** [comment]
Your comment helped a lot. I needed to add `TotalVariation` [here](https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/fa92d081a3c4743a5f34c89141e66ba1c796f21b/CMakeLists.txt#L78). Now I am getting other compile errors, which I am looking into. Thanks!

**Comment by dzenanz** [comment]
This gets much further on my computer:
```text
1>------ Build started: Project: ITKImageProcessingServer, Configuration: Debug x64 ------
1>Automatic MOC for target ITKImageProcessingServer
1>mocs_compilation.cpp
1>ITKProxTVImage.cpp
1>ITKImageProcessingPlugin.cpp
1>LINK : fatal error LNK1104: cannot open file 'OpenMP::OpenMP_CXX.lib'
1>Done building project "ITKImageProcessingServer.vcxproj" -- FAILED.
2>------ Build started: Project: ITKImageProcessingGui, Configuration: Debug x64 ------
2>Automatic MOC for target ITKImageProcessingGui
2>LINK : fatal error LNK1104: cannot open file 'OpenMP::OpenMP_CXX.lib'
2>Done building project "ITKImageProcessingGui.vcxproj" -- FAILED.
3>------ Build started: Project: ITKImageProcessingUnitTest, Configuration: Debug x64 ------
3>Automatic MOC for target ITKImageProcessingUnitTest
3>LINK : fatal error LNK1104: cannot open file 'OpenMP::OpenMP_CXX.lib'
3>Done building project "ITKImageProcessingUnitTest.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 5 up-to-date, 0 skipped ==========
```
`OpenMP` comes from [this line](https://github.com/phcerdan/proxTV/blob/ea3aecaca062dd3a0593c6e31ba5f7762e21b98f/CMakeLists.txt#L69) on [`use_eigen` branch](https://github.com/phcerdan/proxTV/blob/use_eigen/CMakeLists.txt#L69).

After [PR1](https://github.com/phcerdan/proxTV/pull/1) was merged, this compiles without issue!

**Comment by dzenanz** [comment]
@imikejackson @thewtex this is ready for independent testing/merging! It worked with a simple 2D image on my computer.

**Comment by imikejackson** [comment]
It might be a few days before I can get to the merge (for both this one and the one for the Superbuild).

**Comment by dzenanz** [comment]
I am not in a hurry 🐌 😄

**Pull request merged**
