### PR TITLE
WIP: Automatic filters from json no dim vec all filters

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by imikejackson** [comment]
I took a very quick look at just the generate Doc files and while we now have the doc files themselves the content inside the file is just the template (with all the proper substitutions. How hard would it be to extract documentation from the actual ITK source? Or just a summary from the ITK doc source with a link to somewhere online that describes the filters.

My fear is that we just added ~75 filters that we need to have some documentation for. We (BlueQuartz) struggle with adding 3 or 4 filters at a time. I just do not want to let the docs get even further behind.

I'll try to take a look at the generated codes on Tuesday.

Thanks.

**Comment by fbudin69500** [comment]
@imikejackson Yes, the generated doc files for now are empty, but the JSON files do contain a description of the filters. My plan is to add that to the doc files so that users actually know what the different filters do.

**Comment by imikejackson** [comment]
Started looking at the generated code and it is looking really good. One small thing would be to change the generated Human Label to remove the extra "ITK" in the name. Currently there is:

"[ITK] ITK  Abs Image Filter (KW)"; 

Which should just be:

"[ITK] Abs Image Filter (KW)";

**Comment by imikejackson** [comment]
Also, if you could use "clang-format" to format the code before pushing that would be great. There is already a .clang-format file in the plugin that will format the code to the DREAM.3D specs.

**Comment by imikejackson** [comment]
I think we also need to add some #pragmas to turn off warnings about inconsistent-override for the clang builds as we are getting about 1000 warnings. Is the python code that generates the files included in this repository?

**Comment by fbudin69500** [comment]
Thanks for the review. Yes, the python code is in the "Utilities"
sub-directory. I am still working on it to improve it though (add tests and
documentations).

**Pull request closed without merging**
