### PR TITLE
ENH: Add ITKPatchBasedDenoisingImage filter

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:+1:

**Review by imikejackson — APPROVED** [review]

**Comment by fbudin69500** [comment]
@thewtex Any chance you can run this test in docker on your machine to see if you reproduce this problem?

**Comment by thewtex** [comment]
@fbudin69500 Yes, will do.

**Comment by fbudin69500** [comment]
@thewtex thanks

**Comment by thewtex** [comment]
@fbudin69500 I can reproduce the failing test.

**Comment by fbudin69500** [comment]
@thewtex Thanks

**Pull request merged**
