### PR TITLE
ENH: Move Review filters to appropriate category

### PR DESCRIPTION
**Pull request by fbudin69500**
ITK review module is a place-holder while the filters are under consideration
for approval. It does not characterize what type of processing the filter does.
Filters belonging to this module are manually updated to be sorted correctly.

### CODE REVIEW

**Comment by fbudin69500** [comment]
@thewtex @imikejackson Addressing issue #42

**Review by thewtex — CHANGES_REQUESTED** [review]
Thanks for the update!

I think these should go into "ITK MathematicalMorphology".  See http://www.insight-journal.org/browse/publication/65

**Comment by fbudin69500** [comment]
@thewtex Makes sense. Addressed.

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
:1st_place_medal:

**Pull request merged**
